# Generated by Django 4.2.1 on 2023-05-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionJapanese2latin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese_text', models.CharField(max_length=200)),
                ('latin_text', models.CharField(max_length=200)),
            ],
        ),
    ]
