# Generated by Django 4.2.1 on 2023-05-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese2latin', '0002_alter_questionjapanese2latin_japanese_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionjapanese2latin',
            name='japanese_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionjapanese2latin',
            name='latin_text',
            field=models.CharField(max_length=200),
        ),
    ]
