# Generated by Django 4.2.1 on 2023-05-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latin2japanese', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlatin2japanese',
            name='japanese_text',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='questionlatin2japanese',
            name='latin_text',
            field=models.CharField(max_length=10),
        ),
    ]
